version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_shop_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_shop_db
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
